version: '3.5'
services:
  sq-pessoas-api:
    container_name: sq_pessoas_api
    image: sqxp/sq-pessoas-api
    ports:
      - 8080:80
    networks:
      - sq_pessoas_api_network
networks:
  sq_pessoas_api_network:
    driver: bridge
    name: sq_pessoas_api_network
